import { FxDatabase } from '../types';

export const FX_DATABASE: FxDatabase = {
    vocal: [
        { id: 'vocal_whisper', label: 'Whispered Delivery', description: 'Soft, breathy vocals with extreme close-mic intimacy.' },
        { id: 'vocal_telephone', label: 'Telephone Filter', description: 'Narrow band-pass filter, lo-fi radio aesthetic.' },
        { id: 'vocal_reverb_wash', label: 'Heavy Reverb Wash', description: '100% wet ethereal reverb, cathedral-like space.' },
        { id: 'vocal_double_tracked', label: 'Double-Tracked Vocals', description: 'Two lead takes panned slightly left/right for thickness.' },
        { id: 'vocal_vocoder', label: 'Vocoder / Talkbox', description: 'Robotic, modulated synth-voice textures.' },
        { id: 'vocal_gang_chants', label: 'Gang Chants', description: 'Multiple voices shouting in unison, stadium atmosphere.' },
        { id: 'vocal_gritty', label: 'Gritty Raspiness', description: 'Forced vocal tear, aggressive throat distortion.' },
        { id: 'vocal_slacker', label: 'Slacker Talk-Singing', description: 'Deadpan, rhythmic delivery with playful swagger.' },
        { id: 'vocal_pitch_down', label: 'Pitch-Shifted Down', description: 'Deep, slowed-down "chopped and screwed" vocal tone.' },
        { id: 'vocal_formant', label: 'Formant Shifting', description: 'Gender-neutral or "alien" vocal timbre adjustments.' },
        { id: 'vocal_ethereal', label: 'Ethereal Harmonies', description: 'Layered 3rd and 5th intervals with long delay tails.' },
        { id: 'vocal_screaming', label: 'Screaming/Growling', description: 'High-intensity guttural or fry screams for metal/rock.' },
        { id: 'vocal_opera', label: 'Opera Falsetto', description: 'High-pitched, operatic head voice with wide vibrato.' },
        { id: 'vocal_stutter', label: 'Stutter Effect', description: 'Digital glitching on vocal syllables, rhythmic chopping.' },
        { id: 'vocal_reverse_reverb', label: 'Reverse Reverb', description: 'Pre-delay "ghost" effect leading into the vocal start.' },
        { id: 'vocal_megaphone', label: 'Megaphone Distortion', description: 'Aggressive mid-range saturation, protest-style.' },
        { id: 'vocal_melisma', label: 'Soulful Melisma', description: 'Gospel-style vocal runs and complex flourishes.' },
        { id: 'vocal_dry_monologue', label: 'Dry Monologue', description: 'No effects, spoken word, raw and direct.' },
        { id: 'vocal_breath', label: 'Breath In-takes', description: 'Emphasized natural breathing sounds for realism.' },
        { id: 'vocal_autotune', label: 'Autotune Heavy', description: 'Hard-tuned, "T-Pain" style digital pitch correction.' },
        { id: 'vocal_bitcrushed', label: 'Bitcrushed Vocals', description: '8-bit digital crunch, distorted and lo-fi.' },
        { id: 'vocal_backing_whispers', label: 'Backing Whispers', description: 'Ghostly voices panned 100% wide.' },
        { id: 'vocal_adlibs', label: 'Vocal Ad-libs', description: 'Random interjections like "Yeah!", "Uh-huh", "Let\'s go".' },
        { id: 'vocal_delay_sat', label: 'Delay Saturation', description: 'Echoes that get more distorted with each repeat.' },
        { id: 'vocal_tape_sat', label: 'Tape Saturation', description: 'Warm, analog vocal compression from "reel-to-reel".' },
        { id: 'vocal_harmonizer', label: 'Harmonizer Pedal', description: 'Instant multi-part harmony on a single lead line.' },
        { id: 'vocal_breathy_falsetto', label: 'Breathy Falsetto', description: 'High, airy notes with a lot of "air" in the mix.' },
        { id: 'vocal_mantra', label: 'Chanted Mantra', description: 'Rhythmic, repetitive monotone vocal repetition.' },
        { id: 'vocal_extreme_comp', label: 'Extreme Compression', description: '"In-your-face" vocal with zero dynamic range.' },
        { id: 'vocal_ping_pong', label: 'Ping-Pong Delay', description: 'Vocals bouncing rapidly between left and right ears.' },
        { id: 'vocal_distant', label: 'Distant Shouts', description: 'Vocals sounding like they are 50 meters away in a hall.' },
        { id: 'vocal_crying', label: 'Crying/Sobbing', description: 'Emotional, shaky vocal delivery with audible distress.' },
        { id: 'vocal_fast_rap', label: 'Fast Rap Flow', description: 'Rapid-fire delivery, emphasizing consonants.' },
        { id: 'vocal_percussion', label: 'Vocal Percussion', description: 'Beatboxing or mouth-made rhythmic sounds.' },
        { id: 'vocal_baritone', label: 'Deep Baritone', description: 'Forcing the AI to use its lowest vocal register.' },
        { id: 'vocal_sultry', label: 'Sultry Crooning', description: 'Smooth, jazz-style intimate vocal delivery.' },
        { id: 'vocal_vocoder_harm', label: 'Vocoder Harmonies', description: 'Synth-like multi-voice layers.' },
        { id: 'vocal_lofi_radio', label: 'Lo-fi AM Radio', description: 'Thin, crackly voice from a tiny speaker.' },
        { id: 'vocal_unison', label: 'Layered Unison', description: 'Many people singing the exact same note for power.' },
        { id: 'vocal_fry', label: 'Vocal Fry', description: 'Low-energy, gravelly texture at the end of phrases.' },
        { id: 'vocal_robotic_filter', label: '[Robotic Filter]', description: 'Applies a metallic, processed robotic effect to vocals.' }
    ],
    instrumental: [
        { id: 'inst_12string', label: '12-String Shimmer', description: 'Bright, chorus-like resonance of double strings.' },
        { id: 'inst_fuzzy', label: 'Fuzzy Distortion', description: 'Thick "wall of sound" guitar fuzz, 90s grunge style.' },
        { id: 'inst_sleazy_bass', label: 'Thick Sleazy Bass', description: 'Groovy, saturated bass with a lot of "attitude".' },
        { id: 'inst_palm_muted', label: 'Palm-Muted Riffs', description: 'Chuggy, rhythmic, dampened guitar strings.' },
        { id: 'inst_analog_pads', label: 'Analog Synth Pads', description: 'Warm, drifting polyphonic textures.' },
        { id: 'inst_brass_stabs', label: 'Brass Stabs', description: 'Sharp, aggressive hits from trumpets and trombones.' },
        { id: 'inst_slap_bass', label: 'Slap Bass', description: 'Funky, percussive thumb-slapping on bass strings.' },
        { id: 'inst_pick_scrapes', label: 'Pick Scrapes', description: 'High-pitched screech of a guitar pick on steel strings.' },
        { id: 'inst_funk_plucks', label: 'Clean Funk Plucks', description: 'Bright, compressed, and rhythmic guitar stabs.' },
        { id: 'inst_acoustic_res', label: 'Acoustic Resonance', description: 'Emphasized "wood" sound of hollow instruments.' },
        { id: 'inst_electric_sitar', label: 'Electric Sitar', description: 'Exotic, buzzy string textures for psychedelic vibes.' },
        { id: 'inst_hammer_ons', label: 'Hammer-ons', description: 'Smooth, fluid note transitions on string instruments.' },
        { id: 'inst_808', label: 'Drum Machine 808', description: 'Deep sub-bass kicks and sharp electronic snares.' },
        { id: 'inst_glitch_cutoffs', label: 'Glitchy Cut-offs', description: 'Sudden rhythmic silences in the instrumental.' },
        { id: 'inst_spring_reverb', label: 'Spring Reverb', description: 'Surf-rock style "twangy" echo.' },
        { id: 'inst_leslie', label: 'Leslie Speaker', description: 'Swirling, rotating organ or guitar effect.' },
        { id: 'inst_bitcrush_drums', label: 'Bitcrushed Drums', description: 'Lo-fi, crunchy percussion with digital artifacts.' },
        { id: 'inst_slide_guitar', label: 'Slide Guitar', description: 'Whining, fluid metallic notes (blues/country style).' },
        { id: 'inst_tololoche', label: 'Tololoche Slap', description: 'Acoustic regional bass with heavy string-on-wood hits.' },
        { id: 'inst_requinto', label: 'Requinto Shredding', description: 'Fast, high-pitched Mexican guitar soloing.' },
        { id: 'inst_cello', label: 'Bowed Cello', description: 'Deep, melancholic, and sustained string textures.' },
        { id: 'inst_staccato_strings', label: 'Staccato Strings', description: 'Short, sharp, cinematic violin stabs.' },
        { id: 'inst_nylon', label: 'Nylon String Warmth', description: 'Soft, intimate Spanish guitar tones.' },
        { id: 'inst_feedback', label: 'Feedback Loops', description: 'Growing, sustained screeching guitar noise.' },
        { id: 'inst_wah_wah', label: 'Wah-wah Pedal', description: 'Funky, "talking" guitar filter effect.' },
        { id: 'inst_arp_synths', label: 'Arpeggiated Synths', description: 'Fast, repetitive melodic patterns.' },
        { id: 'inst_ride_cymbal', label: 'Heavy Ride Cymbal', description: 'Jazzy, consistent metallic ringing.' },
        { id: 'inst_double_kick', label: 'Double Kick Drums', description: 'Rapid-fire metal-style drum pedals.' },
        { id: 'inst_rhodes', label: 'Rhodes Piano', description: 'Warm, bell-like electric piano tones.' },
        { id: 'inst_dist_accordion', label: 'Distorted Accordion', description: 'Gritty, traditional instrument with a rock edge.' },
        { id: 'inst_flanged_drums', label: 'Flanged Drums', description: '"Jet-plane" swirling effect on the percussion.' },
        { id: 'inst_harmonics', label: 'Harmonics', description: 'High-pitched, bell-like "chiming" notes.' },
        { id: 'inst_walking_bass', label: 'Walking Bassline', description: 'Constant, moving jazz-style bass movement.' },
        { id: 'inst_muted_trumpet', label: 'Muted Trumpet', description: '"Miles Davis" style thin, jazzy brass.' },
        { id: 'inst_granular', label: 'Granular Synthesis', description: 'Shattered, glitchy, and shimmering textures.' },
        { id: 'inst_power_chords', label: 'Power Chords', description: 'Massive, sustained two-note guitar chords.' },
        { id: 'inst_snare_rolls', label: 'Snare Rolls', description: 'Fast, marching-band style drum transitions.' },
        { id: 'inst_sub_harmonic', label: 'Sub-harmonic Synth', description: 'Bass that is felt more than heard (20Hz-40Hz).' },
        { id: 'inst_tremolo', label: 'Tremolo Picking', description: 'Rapidly repeating a single note (surf/black metal).' },
        { id: 'inst_cowbell', label: 'Cowbell Accent', description: 'Classic "more cowbell" rhythmic percussion.' },
        { id: 'inst_reverb_snare', label: '[Reverb Snare]', description: 'Impact snare hit with a thick, heavy reverb tail.' },
        { id: 'inst_reverse_cymbal', label: '[Reverse Cymbal]', description: 'Inverted cymbal crash to create rising tension.' },
        { id: 'inst_glitchy_artifacts', label: '[Glitchy Artifacts]', description: 'Digital broken sounds and controlled software errors.' },
        { id: 'inst_risers_fallers', label: '[Risers/Fallers]', description: 'Sweeping pitch movements for section transitions.' }
    ],
    ambience: [
        { id: 'amb_vinyl', label: '[Vinyl Crackle]', description: 'Lo-fi surface noise from an old record.' },
        { id: 'amb_engine', label: 'Luxury Engine Rev', description: 'Powerful V12 car engine sounds.' },
        { id: 'amb_whoosh', label: '[Cinematic Whoosh]', description: 'Fast air-rush transition effect for epic intros.' },
        { id: 'amb_clock', label: 'Ticking Clock', description: 'Rhythmic mechanical tension.' },
        { id: 'amb_siren', label: 'Distant Siren', description: 'Urban police/ambulance background noise.' },
        { id: 'amb_wind', label: 'Wind Howl', description: 'Desolate, cold atmospheric wind.' },
        { id: 'amb_rain', label: 'Rain on Window', description: 'Soft, intimate environmental water sounds.' },
        { id: 'amb_thunder', label: 'Thunder Rumble', description: 'Deep, low-frequency storm sounds.' },
        { id: 'amb_crowd', label: 'Crowd Murmur', description: 'Sound of a busy cafe or social gathering.' },
        { id: 'amb_camera', label: 'Camera Shutter', description: 'Rapid mechanical clicks (influencer style).' },
        { id: 'amb_glass', label: 'Glass Shatter', description: 'High-pitched, sharp breaking sound.' },
        { id: 'amb_birds', label: 'Birdsong', description: 'Early morning forest ambiance.' },
        { id: 'amb_city', label: 'City Soundscape', description: 'Distant traffic and urban hum.' },
        { id: 'amb_heartbeat', label: 'Heartbeat', description: 'Rhythmic, muffled "thump-thump" (tension).' },
        { id: 'amb_nature_amb', label: '[Nature Ambiance]', description: 'Sounds of deep forest, rain, or natural wind.' },
        { id: 'amb_city_traffic', label: '[City Traffic]', description: 'Urban roar, car horns, and distant murmurs.' },
        { id: 'amb_sub_bass_drop', label: '[Sub Bass Drop]', description: 'Extreme low-frequency impact for cinematic tension.' },
        { id: 'amb_explosion', label: 'Explosion', description: 'Distant, bass-heavy rumble.' },
        { id: 'amb_static', label: 'Static Noise', description: 'Radio interference and white noise.' },
        { id: 'amb_underwater', label: 'Underwater Muffle', description: 'Submerged, bubbly atmospheric filter.' },
        { id: 'amb_crickets', label: 'Crickets', description: 'Night-time outdoor summer vibes.' },
        { id: 'amb_space', label: 'Space Drone', description: 'Deep, sci-fi metallic hum.' },
        { id: 'amb_money', label: 'Money Jingle', description: 'Coins clinking together.' },
        { id: 'amb_door', label: 'Door Slam', description: 'Heavy mechanical impact with reverb.' },
        { id: 'amb_footsteps', label: 'Footsteps', description: 'Rhythmic walking on gravel or wood.' },
        { id: 'amb_fire', label: 'Fire Crackle', description: 'Warm, cozy wood-burning sounds.' },
        { id: 'amb_airport', label: 'Airport Intercom', description: 'Muffled, distant public announcements.' },
        { id: 'amb_glitch', label: 'Glitch Buzz', description: 'Electrical short-circuit sounds.' },
        { id: 'amb_deep_sea', label: 'Deep Sea Echo', description: 'Sonar pings and deep water pressure.' },
        { id: 'amb_jungle', label: 'Jungle Sounds', description: 'Monkeys, birds, and thick foliage rustling.' },
        { id: 'amb_tape_hiss', label: 'Old Tape Hiss', description: 'Authentic analog background noise.' },
        { id: 'amb_police_radio', label: 'Police Radio', description: 'Distant, distorted chatter and beeps.' },
        { id: 'amb_tires', label: 'Screeching Tires', description: 'High-pitched car drift sounds.' },
        { id: 'amb_ocean', label: 'Ocean Waves', description: 'Low-frequency, rhythmic washing sounds.' },
        { id: 'amb_wolf', label: 'Wolf Howl', description: 'Loneliness/darkness thematic sound.' },
        { id: 'amb_keyboard', label: 'Keyboard Typing', description: 'Modern office/hacker aesthetic.' },
        { id: 'amb_children', label: 'Children Playing', description: 'Distant, nostalgic playground sounds.' },
        { id: 'amb_clockwork', label: 'Clockwork Gears', description: 'Mechanical ticking and grinding.' },
        { id: 'amb_subway', label: 'Subway Train', description: 'Deep rumble and metallic screech of tracks.' },
        { id: 'amb_bell', label: 'Bell Toll', description: 'Deep, mournful church bell ringing.' },
        { id: 'amb_alien', label: 'Alien Chatter', description: 'Strange, unidentifiable vocalizations.' },
        { id: 'amb_industrial', label: 'Industrial Clang', description: 'Heavy metal-on-metal rhythmic hits.' },
        { id: 'amb_champagne', label: 'Champagne Pop', description: 'Celebration/luxury sound of a cork popping.' }
    ],
    production: [
        { id: 'prod_wide_stereo', label: 'Wide Stereo', description: 'Maximum width using mid-side expansion.' },
        { id: 'prod_sidechain', label: 'Sidechain Compression', description: 'Pumping effect triggered by the kick.' },
        { id: 'prod_warm_sat', label: 'Warm Saturation', description: 'Analog heat for digital instruments.' },
        { id: 'prod_high_pass', label: 'High-Pass Sweep', description: 'Gradually removing bass for transitions.' },
        { id: 'prod_parallel', label: 'Parallel Compression', description: 'Punchy, aggressive drum and vocal mix.' },
        { id: 'prod_mid_side', label: 'Mid-Side EQ', description: 'Separating center and side frequencies.' },
        { id: 'prod_dynamic', label: 'Dynamic Range', description: 'High contrast between quiet and loud parts.' },
        { id: 'prod_limiter', label: 'Limiter Pumping', description: 'Intentionally over-compressed "hot" master.' },
        { id: 'prod_tube', label: 'Tube Preamp', description: 'Adding "air" and vintage harmonic distortion.' },
        { id: 'prod_phased', label: 'Phased Signal', description: 'Swirling, rotating frequency movement.' },
        { id: 'prod_gate', label: 'Gate Effect', description: 'Cutting off sounds abruptly below a volume.' },
        { id: 'prod_reverse_echo', label: 'Reverse Echo', description: 'Echoes that appear before the sound starts.' },
        { id: 'prod_brickwall', label: 'Brickwall Limiting', description: 'Maximum loudness without clipping.' },
        { id: 'prod_tape_flange', label: 'Tape Flanging', description: 'Jet-plane effect on the entire master.' },
        { id: 'prod_mono', label: 'Mono Compatibility', description: 'Ensuring the mix is solid in mono.' },
        { id: 'prod_delay_14', label: '1/4 Note Delay', description: 'Rhythmic echoes synced to the beat.' },
        { id: 'prod_slapback', label: 'Slapback Echo', description: 'Single, very fast repeat (50s rock style).' },
        { id: 'prod_convolution', label: 'Convolution Reverb', description: 'Real-world room IR (Industrial, Cave, Hall).' },
        { id: 'prod_exciter', label: 'Exciter', description: 'Adding artificial high-end "shimmer" to vocals.' },
        { id: 'prod_low_boost', label: 'Low-End Boost', description: 'Sub-bass focus around 50Hz.' },
        { id: 'prod_high_shelf', label: 'High-Shelf Cut', description: 'Muffling the high frequencies for "lo-fi".' },
        { id: 'prod_ping_pong', label: 'Stereo Ping-Pong', description: 'Alternating audio between speakers.' },
        { id: 'prod_pitch_drift', label: 'Pitch Drift', description: 'Subtle "out of tune" analog tape feel.' },
        { id: 'prod_phase_inv', label: 'Phase Inversion', description: 'Creating hollow or "out-of-phase" textures.' },
        { id: 'prod_transient', label: 'Transient Shaper', description: 'Making drums hit harder or softer.' },
        { id: 'prod_multiband', label: 'Multiband Compression', description: 'Controlling specific frequency ranges.' },
        { id: 'prod_dry_wet', label: 'Dry/Wet Balance', description: 'Mixing clean and processed signals.' },
        { id: 'prod_binaural', label: 'Binaural Audio', description: '3D-headphone-optimized sound placement.' },
        { id: 'prod_tempo_mod', label: 'Tempo Modulation', description: 'Gradual speeding up or slowing down.' },
        { id: 'prod_bit_depth', label: 'Bit-Depth Reduction', description: 'Lowering digital quality for "grit".' },
        { id: 'prod_harmonic', label: 'Harmonic Exciter', description: 'Enhancing mid-range presence.' },
        { id: 'prod_plate', label: 'Plate Reverb', description: 'Classic metallic, bright studio reverb.' },
        { id: 'prod_gated', label: 'Gated Reverb', description: '80s-style drums that cut off instantly.' },
        { id: 'prod_vibrato', label: 'Vibrato Depth', description: 'Modulating pitch for an "unstable" feel.' },
        { id: 'prod_duck', label: 'Duck Reverb', description: 'Reverb only appears when the singer is silent.' },
        { id: 'prod_wide_pan', label: 'Wide Panning', description: 'Guitars 100% L/R, Vocals 0% Center.' },
        { id: 'prod_sample_rate', label: 'Sample Rate Reduction', description: 'Creating "aliasing" noise.' },
        { id: 'prod_soft_clip', label: 'Soft Clipping', description: 'Gentle distortion for added loudness.' },
        { id: 'prod_infinite', label: 'Infinite Sustain', description: 'Instruments that never stop ringing out.' },
        { id: 'prod_sudden_mute', label: 'Sudden Mute', description: 'Zero sound for exactly 1 beat for impact.' }
    ]
};
